{
 "title": "core-waap",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "CRS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocked Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(idelta(waf_filter_tx_interruptions_ruleid_949110_phase_http_request_body[5m]))",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(idelta(waf_filter_tx_total[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Application Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(envoy_response_code_class) (idelta(envoy_listener_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"core-waap\"}[5m]))",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(idelta(envoy_http_downstream_rq_time_sum{envoy_http_conn_manager_prefix=\"core-waap\"}[5m])) / sum(idelta(envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix=\"core-waap\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Bytes Transferred",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(idelta(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=\"core-waap\"}[5m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CRS 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocked Requests",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(job) (waf_filter_tx_interruptions_ruleid_949110_phase_http_request_body)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(job) (waf_filter_tx_total)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}