title = 'USP Core WAAP documentation'
theme = 'github.com/united-security-providers/usp-docs-hugo-theme'
copyright = '&copy; 2026 United Security Providers AG. All Rights Reserved.'

baseURL = 'https://docs.united-security-providers.ch/'
relativeURLs = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

disableKinds = ['taxonomy', 'term', 'rss']
disablePathToLower = true

[languages.en]
contentDir = 'content/en'
label = 'English'
weight = 1

[outputs]
home = ['html', 'markdown', 'llms']
section = ['html', 'markdown']
page = ['html', 'markdown']

[outputFormats.llms]
mediaType = 'text/plain'
baseName = 'llms'
isPlainText = true
notAlternative = true

[outputFormats.markdown]
mediaType = 'text/markdown'
baseName = 'index'
isPlainText = true

[markup.goldmark.extensions.typographer]
disable = true

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[params]
description = 'Configuration, operation and release notes for the USP Core WAAP (Web Application and API Protection).'
canonicalBase = 'https://docs.united-security-providers.ch/usp-core-waap/'
logo = 'images/USP-Logo-2023-ohne-claim-lang-white1.webp'
eol = []

[params.search]
enabled = true

[[params.social]]
icon = 'linkedin'
link = 'https://www.linkedin.com/company/united-security-providers/'
name = 'United Security Providers on Linkedin'

[[params.social]]
icon = 'youtube'
link = 'https://www.youtube.com/@United-security-providersCh'
name = 'United Security Providers on Youtube'
