apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contour-ingress
  namespace: juiceshop
  annotations:
    projectcontour.io/websocket-routes: /
    cert-manager.io/cluster-issuer: cert-issuer
spec:
  rules:
    - host: {{.Values.hostnames.direct}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: juice-shop
                port:
                  number: 8000

    - host: {{.Values.hostnames.viaCoreWaap}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: usp-core-waap
                port:
                  number: 8080
    - host: {{.Values.hostnames.coreWaapAdmin}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core-waap-admin-if
                port:
                  number: 8001
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - {{.Values.hostnames.direct}}
    - {{.Values.hostnames.viaCoreWaap}}
    - {{.Values.hostnames.coreWaapAdmin}}
    # by convention name of ingress from above plus "-cert":
    secretName: contour-ingress-cert # < cert-manager will store the created certificate in this secret.