apiVersion: v1
kind: Secret
metadata:
  name: uwe-hmac-secret-ref
  namespace: juiceshop
type: Opaque
stringData:
  hmacSecret.yaml: |
    resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      name: uwe-hmac-secret-ref
      genericSecret:
        secret:
          inlineString: "hmacJanuar2024"