apiVersion: v1
kind: Secret
metadata:
  name: uwe-client-secret-ref
  namespace: juiceshop
type: Opaque
stringData:
  clientSecret.yaml: |
    resources:
    - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
      name: uwe-client-secret-ref
      genericSecret:
        secret:
          inlineString: "clientSecretjanuar2024"
