apiVersion: waap.core.u-s-p.ch/v1alpha1
kind: CoreWaapService
metadata:
  name: core-waap
  namespace: juiceshop
  annotations:
    # for hot-restart to work it needs twice as much memory as
    # for one instance
    core.waap.u-s-p.ch/limits-memory: 1000Mi
    #core.waap.u-s-p.ch/custom-cacerts: ca-certificates
spec:
  hostnames:
    - {{.Values.hostnames.viaCoreWaap}}:8080
    - {{.Values.hostnames.viaCoreWaap}}:8443
  websocket: True
  crs:
    mode: BLOCK
    securityLevel: 5
    paranoiaLevel: 1
    requestBodyAccess: true
    requestBodyLimit: 2147483646

    parseXml: true
    parseJson: true
    validateJson: true
    responseBodyLimit: 131072
    enabledRequestRules: [911, 913, 921, 922, 930, 931, 932, 933, 934, 941, 942, 943, 944]
    requestRuleExceptions:
      - ruleId: 941160
        requestPartType: ARGS_POST
        requestPartName: json.email
        location: /rest/user/login
    enabledResponseRules: [950, 951, 952, 953, 954, 955]
    
  routes:
    - match:
        path: "/"
        pathType: "PREFIX"
      backend:
        address: juice-shop
        port: 8000
      auth:
        ref: "myauth"
  authentication:
    - name: "myauth"
      #issuer: "https://sestest2.seslab.local/ite/oidc-op/sls"
      #authorizationEndpoint: "https://sestest2.seslab.local/ite/oidc-op/sls/auth"
      #tokenEndpoint: "https://sestest2.seslab.local/ite/oidc-op/sls/oidc-token"
      issuer: "https://cloudses.online/login/sls"
      authorizationEndpoint: "https://cloudses.online/login/sls/oidc-auth"
      tokenEndpoint: "https://cloudses.online/login/sls/oidc-token"
      tokenEndpointAuthType: "QUERY"
      credentials:
        clientId: "uwe-client"
        #clientSecret: "clientSecretjanuar2024"
        clientSecretRef: "uwe-client-secret-ref"
        # redirect URI for OP config (https):
        # https://juiceshop-via-core-waap-10-99-0-10.nip.io:8443/oauth-myauth-callback
        #hmacSecret: "hmacJanuar2024"
        hmacSecretRef: "uwe-hmac-secret-ref"
      #jwksEndpoint: "https://sestest2.seslab.local/ite/oidc-op/sls/.well-known/openid-configuration/jwks"
      jwksEndpoint: "https://cloudses.online/login/sls/.well-known/openid-configuration/jwks"
      jwksSymmetricKey: "myjwkssymkey-ignored-so-far"
      scopes:
        - "openid"
      #audience:
        #- "..."
      backend:
        forwardJwt: true
        jwtProcessingEndpoint: "https://ignored-so-far/"
        jwtClaimToHeader:
          - claim: "sub-ignored-so-far"
            headerName: "x-user-ignored-so-far"
