# USP Core WAAP Operator configuration values
# NOTE: The values documentation on the Core WAAP website (https://united-security-providers.github.io/usp-core-waap/values/)
# is generated directly from the contents of this file, which is why Markdown formatting elements are used in the
# comments, and why each comment documenting a setting must start with "--" (requirement of the tool used to convert
# this YAML file to Markdown).

operator:

  # -- Version of operator to deploy
  version: "0.5.0"

  # -- Operator container image
  image: "quay.io/usp/usp-core-waap-operator"

  # -- Operator deployment namespace
  namespace: "usp-core-waap-operator"

  # -- _Optional_: list of namespaces for which to process custom resources or ingress manifests (defaults to all).
  watchedNamespaces: ""

  # -- _Optional_: If set to true, envoy will be deployed as an ingress proxy in the operators own namespace
  ingressMode: false

  # -- _Optional_: name of ConfigMap which holds the CA truststore to be used by default (globally) in the pod.
  caCertsConfigMapName: "ca-certificates"

  # -- Mandatory if caCertificatesConfigMapName is set:
  # name of key in ConfigMap which holds the CA truststore. The entry with that key name
  # will be mapped to the "ca-certificates.crt" file.
  caCertKeyInConfigMap: "ca-certificates.crt"

  # -- Name of service account
  serviceAccount: "usp-core-waap-operator"

envoy:

  # -- image: The Envoy container image to use
  image: "quay.io/usp/usp-core-waap"

  # -- _Optional_: Additional label(s) for Envoy pods
  # Must be comma- or blank-separated key/value pairs.
  # Example:
  # ```"creator=usp logformat=json"```
  labels: ""

  # -- _Optional_: Number of pod replicas
  # If not set, the field is not seen as "managed by the operator", meaning the operator
  # won't undo any changes to this field done by the HPA (Horizontal Pod Autoscaler).
  replicas: 1

  # -- _Optional_: Listener port of k8s service created by the operator for the envoy proxy
  servicePort: 8080

  # -- _Optional_: Envoy proxy listener port (usually only needed if a custom image is used where envoy does not listen on 8080)
  listenerPort: 8080

  # Resource settings for Envoy pods
  resources:
    request:
      # -- CPU resources required per request
      cpu: "1.0"
      # -- Memory resources required per request
      memory: "300Mi"
    limits:
      # -- CPU resource limit per request
      cpu: "1500m"
      # -- Memory resource limit per request
      memory: "500Mi"

  # Optional GeoIP provider configuration
  geoIpProvider:
    # Settings for MaxMind GeoIP data provider
    maxmind:
      # -- _Optional_: Set to false to disable using the free MaxMind databases.
      useLite: true
      # -- _Optional_: MaxMind account ID for DB download
      accountId: ""
      # -- _Optional_: MaxMind license key for DB download
      licenseKey: ""
    # Settings for ipinfo.io GeoIP data provider
    ipinfo:
      # -- _Optional_: Token string for ipinfo.io DB download
      token: ""


