kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpbin
  namespace: httpbin
spec:
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
  selector:
    matchLabels:
      app: httpbin
