apiVersion: waap.core.u-s-p.ch/v1alpha1
kind: CoreWaapService
metadata:
  name: httpbin-core-waap
  namespace: httpbin
  annotations:
    core.waap.u-s-p.ch/registry: quay.io
    core.waap.u-s-p.ch/version: 1.0.4-rc3
spec:
  hostnames:
    - {{.Values.hostnames.viaCoreWaap}}:8080
  websocket: True
  crs:
    mode: BLOCK
    securityLevel: 5
    paranoiaLevel: 1
    requestBodyAccess: true
    requestBodyLimit: 2147483646

    parseXml: true
    parseJson: true
    validateJson: true
    responseBodyLimit: 131072
    enabledRequestRules:
      - 930
      - 941
      - 942
    requestRuleExceptions:
    
  routes:
    - match:
        path: ^/.*
      backend:
        address: httpbin
        port: 8000
