apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: f31d1dee1022c13241ed29958db11b48d4e2764d
    app.quarkus.io/build-timestamp: 2023-11-08 - 09:09:18 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: {{.Values.operatorVersion}}
    app.kubernetes.io/name: usp-core-waap-operator
  name: core-waap-operator
  namespace: usp-core-waap-operator