kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: core-waap-operator-role # should match roleRef/name in core-waap-operator-role-binding.yaml
  namespace: usp-core-waap-operator
rules:
  - apiGroups: ["waap.core.u-s-p.ch"]
    resources:
      - corewaapservices
      - corewaapservices/status
      - pods
      - pods/exec
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups: [""]
    resources:
      - pods
      - pods/exec
      - configmaps
      - services
      - secrets
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups: ["cert-manager.io"]
    resources:
      - certificates
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update